### ISSUE TITLE
Stunfisk stats

### ISSUE THREAD

**Issue by depressedgay** [charizard8888/Pet-Mods-Workshop#5]
[Fusion Evolution.zip](https://github.com/charizard8888/Pet-Mods-Workshop/files/4067833/Fusion.Evolution.zip)

I fixed the issue on my own but it would probably help to upload it here. However I cannot do that until I upload an issue. For the record Stunfisk had Galarian Stunfisk's stats and the special defense was 10 points higher. Also Galarian Stunfisk had no stats.
[Fusion Evolution.zip](https://github.com/charizard8888/Pet-Mods-Workshop/files/4067836/Fusion.Evolution.zip)

**Comment by charizard8888** [comment]
Added
Thanks!
